name: Check If Tests Were Not Modified
on: [push]

env:
  APP_URL: "http://127.0.0.1:8000"
  APP_ENV: local
  DB_DATABASE: products_management
  DB_USERNAME: root
  DB_PASSWORD: root
  DISABLE_2FA: true

jobs:
  dusk:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - name: Check if tests files were not modified
        run: |
          if git diff --exit-code -- tests/ '*.Test.php'; then
            echo "No changes in test files."
          else
            echo "Test files have been modified. Exiting with error."
            exit 1
          fi
