name: Forge Preview
on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review, closed]

jobs:
  provision:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    environment: test
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    steps:
      - name: Install Harbor via Composer
        run: composer global require mehrancodes/laravel-harbor -q
      - name: Prepare sanitized branch variables
        run: |
          BRANCH="${{ github.head_ref }}"
          SANITIZED=$(echo "$BRANCH" | sed -E 's/^[0-9]+-//' | tr '-' '_' | cut -c1-32)
          echo "FORGE_SITE_ISOLATION_USERNAME=$SANITIZED" >> "$GITHUB_ENV"
          echo "FORGE_DB_NAME=$SANITIZED" >> "$GITHUB_ENV"
      - name: Start Provisioning
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_SERVER: ${{ secrets.FORGE_SERVER_ID }}
          FORGE_DOMAIN: ${{ secrets.FORGE_DOMAIN }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
          FORGE_DEPLOY_SCRIPT: ${{ vars.FORGE_DEPLOY_SCRIPT }}
          FORGE_TIMEOUT_SECONDS: ${{ vars.FORGE_TIMEOUT_SECONDS }}
          FORGE_DB_CREATION_REQUIRED: true
          FORGE_DB_NAME: ${{ env.FORGE_DB_NAME }}
          FORGE_SITE_ISOLATION_USERNAME: ${{ env.FORGE_SITE_ISOLATION_USERNAME }}
          GIT_COMMENT_ENABLED: true
          GIT_TOKEN: ${{ github.token }}
          GIT_ISSUE_NUMBER: ${{ github.event.number }}
        run: harbor provision
  teardown:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    environment: test
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    steps:
      - name: Install Harbor
        run: composer global require mehrancodes/laravel-harbor -q
      - name: Remove Preview Environment
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_SERVER: ${{ secrets.FORGE_SERVER_ID }}
          FORGE_DOMAIN: ${{ secrets.FORGE_DOMAIN }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
        run: harbor teardown
